ports:
  - port: 8080
    onOpen: open-preview
  - port: 3000
    onOpen: ignore
checkoutLocation: "go/src/github.com/demo-apps/go-gin-app"
workspaceLocation: "go/src/github.com/demo-apps/go-gin-app"
tasks:
  - name: Restore Tailscale daemon
    command: |
      if [ -n "${TS_STATE_TAILSCALE_EXAMPLE}" ]; then
        # restore the tailscale state from gitpod user's env vars
        sudo mkdir -p /var/lib/tailscale
        echo "${TS_STATE_TAILSCALE_EXAMPLE}" | sudo tee /var/lib/tailscale/tailscaled.state > /dev/null
      fi
      sudo tailscaled
  - init: >
      go build -o app
    command: >
      ./app
  - name: Connect to Tailscale 
    command: |
      if [ -n "${TS_STATE_TAILSCALE_EXAMPLE}" ]; then
        sudo -E tailscale up
      else
        sudo -E tailscale up --authkey=${TAILSCALE_AUTHKEY} --hostname "gitpod-${GITPOD_GIT_USER_NAME// /-}-$(echo ${GITPOD_WORKSPACE_CONTEXT} | jq -r .repository.name)"
        # store the tailscale state into gitpod user
        gp env TS_STATE_TAILSCALE_EXAMPLE="$(sudo cat /var/lib/tailscale/tailscaled.state)"
      fi
      exit
github:
    prebuilds:
        pullRequestsFromForks: true
vscode:
  extensions:
    - golang.go